:concurrency: 10
:pidfile: ./tmp/pids/sidekiq.pid
:logfile: ./log/sidekiq.log

:queues:
    - default
    - [report, 10]
    - [myqueue, 1]
    - [mailers, 1]

development:
  :concurrency: 5
staging:
  :concurrency: 10
production:
  :concurrency: 20
