:concurrency: 8
:pidfile: ./tmp/pids/sidekiq.pid
:logfile: ./log/sidekiq.log

:queues:
    - default
    - [generate_pupil_report, 20]
    - [generate_group_report, 20]
    - [construct_report, 20]
    - [import_results, 5]
    - [generate_reports, 20]
    - [score, 5]
    - [monitoring, 1]

development:
  :concurrency: 8
staging:
  :concurrency: 30
production:
  :concurrency: 100
