:concurrency: 10
:pidfile: ./tmp/pids/sidekiq.pid
:logfile: ./log/sidekiq.log

:queues:
    - default
    - [import_results, 1]
    - [generate_reports, 3]

development:
  :concurrency: 10
staging:
  :concurrency: 10
production:
  :concurrency: 20
